### ISSUE TITLE
Offer a option for filter and cropper

### ISSUE THREAD

**Issue by ChokShen** [congnd/FMPhotoPicker#22]
Hi. The library is awesome! But Someone, like me, only need cropper, or someone only need filter, or others don't need both. Maybe you can offer a option as FMPhotoPickerConfig. I mean it's easy to do this. Thx.

**Comment by congnd** [comment]
Thanks for using FMPhotoPicker.
I have heard someone talk about the function like what you've described.
And of course, I think it is a great ideal. But it is a little bit difficult for me to do it right now since my current workload is significantly increased recently, so it would be appreciated if you can wait for a while.

**Comment by congnd** [comment]
@ChokShen 
Sorry for long time no response.

With the release of v1.0.0. You now can use crop or filter feature invidually or you even can make all of them unavailable.
Please read the documentation here for more details.
https://github.com/congnd/FMPhotoPicker#ref-available-filters

Feel free to reopen this again if you need more support.
